import logging
from typing import Any

from ..models.common import NodeType, ScheduleType
from ..models.workflow import GraphDefinition, ScheduleConfig, Workflow, WorkflowEdge, WorkflowNode

logger = logging.getLogger(__name__)

BUILTIN_WORKFLOWS: list[dict[str, Any]] = [
    {
        "name": "invoice-chase",
        "slashCommand": "/invoice-chase",
        "displayName": "逾期发票催收",
        "description": "读取QuickBooks逾期账单，生成催收邮件，人工审批后发送",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "manual"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_read", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_overdue_invoice"}},
                {"id": "n_draft", "type": "SKILL_NODE", "config": {"skillId": "draft-invoice-reminder"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "确认发送催收邮件"}},
                {"id": "n_send", "type": "CONNECTOR_NODE", "config": {"connectorId": "gmail", "action": "send_email"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_read"},
                {"source": "n_read", "target": "n_draft"},
                {"source": "n_draft", "target": "n_approval"},
                {"source": "n_approval", "target": "n_send", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_send", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "lead-nurture",
        "slashCommand": "/lead-nurture",
        "displayName": "线索培育跟进",
        "description": "读取HubSpot新线索，评分后生成跟进邮件，审批后发送",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "manual"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_leads", "type": "CONNECTOR_NODE", "config": {"connectorId": "hubspot", "action": "query_new_leads"}},
                {"id": "n_score", "type": "SKILL_NODE", "config": {"skillId": "score-lead"}},
                {"id": "n_draft", "type": "SKILL_NODE", "config": {"skillId": "email-draft"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "确认发送跟进邮件"}},
                {"id": "n_send", "type": "CONNECTOR_NODE", "config": {"connectorId": "gmail", "action": "send_email"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_leads"},
                {"source": "n_leads", "target": "n_score"},
                {"source": "n_score", "target": "n_draft"},
                {"source": "n_draft", "target": "n_approval"},
                {"source": "n_approval", "target": "n_send", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_send", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "cash-flow-alert",
        "slashCommand": "/cash-flow-alert",
        "displayName": "现金流预警",
        "description": "定时读取财务数据，生成现金流快照，低余额自动预警通知",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "0 9 * * 1"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_read", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_transactions"}},
                {"id": "n_snapshot", "type": "SKILL_NODE", "config": {"skillId": "cash-flow-snapshot"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "cash_flow_report"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_read"},
                {"source": "n_read", "target": "n_snapshot"},
                {"source": "n_snapshot", "target": "n_output"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "weekly-sales",
        "slashCommand": "/weekly-sales",
        "displayName": "周销售报告",
        "description": "每周自动生成销售报告，推送到Slack频道",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "0 10 * * 1"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_sales", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_sales"}},
                {"id": "n_report", "type": "SKILL_NODE", "config": {"skillId": "weekly-sales-report"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "sales_report"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_sales"},
                {"source": "n_sales", "target": "n_report"},
                {"source": "n_report", "target": "n_output"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "expense-review",
        "slashCommand": "/expense-review",
        "displayName": "支出审查",
        "description": "自动分类支出，生成异常支出预警，需要财务审批",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "manual"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_expenses", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_expenses"}},
                {"id": "n_categorize", "type": "SKILL_NODE", "config": {"skillId": "expense-categorize"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "确认支出分类结果"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "expense_report"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_expenses"},
                {"source": "n_expenses", "target": "n_categorize"},
                {"source": "n_categorize", "target": "n_approval"},
                {"source": "n_approval", "target": "n_output", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "customer-health",
        "slashCommand": "/customer-health",
        "displayName": "客户健康度检查",
        "description": "分析客户沟通记录情绪，生成健康度评分报告",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "manual"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_emails", "type": "CONNECTOR_NODE", "config": {"connectorId": "gmail", "action": "query_emails"}},
                {"id": "n_sentiment", "type": "SKILL_NODE", "config": {"skillId": "customer-sentiment"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "customer_health"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_emails"},
                {"source": "n_emails", "target": "n_sentiment"},
                {"source": "n_sentiment", "target": "n_output"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "contract-review",
        "slashCommand": "/contract-review",
        "displayName": "合同审查",
        "description": "读取DocuSign合同，提取要点，审批后归档",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "manual"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_contract", "type": "CONNECTOR_NODE", "config": {"connectorId": "docusign", "action": "query_contract"}},
                {"id": "n_summary", "type": "SKILL_NODE", "config": {"skillId": "contract-summary"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "确认合同审查结果"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "contract_review"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_contract"},
                {"source": "n_contract", "target": "n_summary"},
                {"source": "n_summary", "target": "n_approval"},
                {"source": "n_approval", "target": "n_output", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "tax-filing-reminder",
        "slashCommand": "/tax-reminder",
        "displayName": "税务申报提醒",
        "description": "根据财务数据生成税务提醒，审批后发送通知",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "0 9 1 * *"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_transactions", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_transactions"}},
                {"id": "n_tax", "type": "SKILL_NODE", "config": {"skillId": "tax-reminder"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "确认税务提醒内容"}},
                {"id": "n_notify", "type": "CONNECTOR_NODE", "config": {"connectorId": "slack", "action": "send_message"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_transactions"},
                {"source": "n_transactions", "target": "n_tax"},
                {"source": "n_tax", "target": "n_approval"},
                {"source": "n_approval", "target": "n_notify", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_notify", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "inventory-check",
        "slashCommand": "/inventory-check",
        "displayName": "库存盘点预警",
        "description": "读取库存数据，分析预警，生成补货建议",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "0 8 * * 1-5"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_inventory", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_inventory"}},
                {"id": "n_alert", "type": "SKILL_NODE", "config": {"skillId": "inventory-alert"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "inventory_alert"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_inventory"},
                {"source": "n_inventory", "target": "n_alert"},
                {"source": "n_alert", "target": "n_output"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "payroll-process",
        "slashCommand": "/payroll",
        "displayName": "薪资处理",
        "description": "计算薪资摘要，审批后确认发放",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "0 10 25 * *"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_hours", "type": "CONNECTOR_NODE", "config": {"connectorId": "m365", "action": "query_timesheets"}},
                {"id": "n_calc", "type": "SKILL_NODE", "config": {"skillId": "payroll-summary"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "确认薪资发放"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "payroll_report"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_hours"},
                {"source": "n_hours", "target": "n_calc"},
                {"source": "n_calc", "target": "n_approval"},
                {"source": "n_approval", "target": "n_output", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "slack-daily-digest",
        "slashCommand": "/slack-digest",
        "displayName": "Slack每日摘要",
        "description": "汇总Slack频道消息，生成每日工作摘要",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "30 18 * * 1-5"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_messages", "type": "CONNECTOR_NODE", "config": {"connectorId": "slack", "action": "query_messages"}},
                {"id": "n_digest", "type": "SKILL_NODE", "config": {"skillId": "slack-digest"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "daily_digest"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_messages"},
                {"source": "n_messages", "target": "n_digest"},
                {"source": "n_digest", "target": "n_output"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "invoice-validation",
        "slashCommand": "/invoice-validate",
        "displayName": "发票合规校验",
        "description": "读取发票数据，自动校验合规性，异常发票需审批",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "manual"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_invoices", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_invoices"}},
                {"id": "n_validate", "type": "SKILL_NODE", "config": {"skillId": "invoice-validate"}},
                {"id": "n_condition", "type": "CONDITION_NODE", "config": {"conditionExpr": "has_anomaly"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "异常发票需确认"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "validation_result"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_invoices"},
                {"source": "n_invoices", "target": "n_validate"},
                {"source": "n_validate", "target": "n_condition"},
                {"source": "n_condition", "target": "n_approval", "condition": "anomaly"},
                {"source": "n_condition", "target": "n_output", "condition": "default"},
                {"source": "n_approval", "target": "n_output", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "kpi-dashboard",
        "slashCommand": "/kpi",
        "displayName": "KPI仪表盘更新",
        "description": "汇总财务和客户数据，更新KPI仪表盘",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "0 8 * * 1-5"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_finance", "type": "CONNECTOR_NODE", "config": {"connectorId": "quickbooks", "action": "query_financials"}},
                {"id": "n_customers", "type": "CONNECTOR_NODE", "config": {"connectorId": "hubspot", "action": "query_customers"}},
                {"id": "n_kpi", "type": "SKILL_NODE", "config": {"skillId": "kpi-dashboard-data"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "kpi_data"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_finance"},
                {"source": "n_finance", "target": "n_customers"},
                {"source": "n_customers", "target": "n_kpi"},
                {"source": "n_kpi", "target": "n_output"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "competitor-watch",
        "slashCommand": "/competitor-watch",
        "displayName": "竞品监控",
        "description": "收集市场数据，生成竞品动态简报",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "cron", "cron": "0 9 * * 1"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_market", "type": "CONNECTOR_NODE", "config": {"connectorId": "hubspot", "action": "query_market_data"}},
                {"id": "n_brief", "type": "SKILL_NODE", "config": {"skillId": "competitor-brief"}},
                {"id": "n_output", "type": "OUTPUT_NODE", "config": {"outputKey": "competitor_brief"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_market"},
                {"source": "n_market", "target": "n_brief"},
                {"source": "n_brief", "target": "n_output"},
                {"source": "n_output", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
    {
        "name": "multi-channel-outreach",
        "slashCommand": "/outreach",
        "displayName": "多渠道触达",
        "description": "根据客户偏好，通过邮件和Slack发送定制消息，需审批",
        "version": "1.0",
        "enabled": True,
        "schedule": {"type": "manual"},
        "graphDefinition": {
            "nodes": [
                {"id": "n_start", "type": "START_NODE"},
                {"id": "n_customers", "type": "CONNECTOR_NODE", "config": {"connectorId": "hubspot", "action": "query_contacts"}},
                {"id": "n_draft_email", "type": "SKILL_NODE", "config": {"skillId": "email-draft"}},
                {"id": "n_approval", "type": "APPROVAL_GATE_NODE", "config": {"title": "确认多渠道消息内容"}},
                {"id": "n_send_email", "type": "CONNECTOR_NODE", "config": {"connectorId": "gmail", "action": "send_email"}},
                {"id": "n_send_slack", "type": "CONNECTOR_NODE", "config": {"connectorId": "slack", "action": "send_message"}},
                {"id": "n_end", "type": "END_NODE"},
            ],
            "edges": [
                {"source": "n_start", "target": "n_customers"},
                {"source": "n_customers", "target": "n_draft_email"},
                {"source": "n_draft_email", "target": "n_approval"},
                {"source": "n_approval", "target": "n_send_email", "condition": "approved"},
                {"source": "n_approval", "target": "n_end", "condition": "denied"},
                {"source": "n_send_email", "target": "n_send_slack"},
                {"source": "n_send_slack", "target": "n_end"},
            ],
            "entryNode": "n_start",
        },
    },
]


def get_builtin_workflows() -> list[Workflow]:
    return [Workflow(**w) for w in BUILTIN_WORKFLOWS]
