import logging
from typing import Any

from ..models.common import ActionSchema, SkillType
from ..models.skill import Skill

logger = logging.getLogger(__name__)

BUILTIN_SKILLS: list[dict[str, Any]] = [
    {
        "skillId": "cash-flow-snapshot",
        "name": "cash-flow-snapshot",
        "displayName": "现金流快照",
        "type": SkillType.PROMPT,
        "definition": "根据以下交易数据，生成现金流快照摘要：收入、支出、净额、趋势分析",
        "inputSchema": {"type": "object", "properties": {"transactions": {"type": "array"}, "period": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "draft-invoice-reminder",
        "name": "draft-invoice-reminder",
        "displayName": "生成催收邮件",
        "type": SkillType.PROMPT,
        "definition": "根据逾期发票信息，生成专业催收邮件，包含发票号、金额、逾期天数、付款链接",
        "inputSchema": {"type": "object", "properties": {"invoices": {"type": "array"}, "companyName": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "score-lead",
        "name": "score-lead",
        "displayName": "线索评分",
        "type": SkillType.PROMPT,
        "definition": "根据客户互动数据，对线索进行评分(1-100)，包含评分理由和推荐动作",
        "inputSchema": {"type": "object", "properties": {"leadData": {"type": "object"}, "interactionHistory": {"type": "array"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "weekly-sales-report",
        "name": "weekly-sales-report",
        "displayName": "周销售报告生成",
        "type": SkillType.PROMPT,
        "definition": "根据本周销售数据，生成销售摘要报告：总销售额、订单数、top产品、同比变化",
        "inputSchema": {"type": "object", "properties": {"salesData": {"type": "array"}, "weekRange": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "expense-categorize",
        "name": "expense-categorize",
        "displayName": "支出自动分类",
        "type": SkillType.PROMPT,
        "definition": "将支出交易自动分类到标准类别：办公、差旅、营销、薪资、租金、其他",
        "inputSchema": {"type": "object", "properties": {"transactions": {"type": "array"}, "categories": {"type": "array"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "customer-sentiment",
        "name": "customer-sentiment",
        "displayName": "客户情绪分析",
        "type": SkillType.PROMPT,
        "definition": "分析客户沟通记录的情绪倾向：正面、中性、负面，给出关键情绪指标",
        "inputSchema": {"type": "object", "properties": {"messages": {"type": "array"}, "customerName": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "contract-summary",
        "name": "contract-summary",
        "displayName": "合同要点摘要",
        "type": SkillType.PROMPT,
        "definition": "提取合同关键条款：签约方、金额、有效期、违约责任、特殊条款",
        "inputSchema": {"type": "object", "properties": {"contractText": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "tax-reminder",
        "name": "tax-reminder",
        "displayName": "税务提醒生成",
        "type": SkillType.PROMPT,
        "definition": "根据地区和交易数据，生成税务申报提醒：税种、截止日期、预估金额",
        "inputSchema": {"type": "object", "properties": {"transactions": {"type": "array"}, "region": {"type": "string"}, "period": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "email-draft",
        "name": "email-draft",
        "displayName": "邮件草稿生成",
        "type": SkillType.PROMPT,
        "definition": "根据上下文生成商务邮件草稿，支持多种场景：报价、跟进、感谢、投诉回复",
        "inputSchema": {"type": "object", "properties": {"scenario": {"type": "string"}, "context": {"type": "object"}, "recipient": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "inventory-alert",
        "name": "inventory-alert",
        "displayName": "库存预警分析",
        "type": SkillType.PROMPT,
        "definition": "分析库存数据，识别低库存、滞销、断货风险商品，给出补货建议",
        "inputSchema": {"type": "object", "properties": {"inventoryData": {"type": "array"}, "thresholdDays": {"type": "integer"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "payroll-summary",
        "name": "payroll-summary",
        "displayName": "薪资摘要计算",
        "type": SkillType.PROMPT,
        "definition": "根据员工工时和薪资数据，生成薪资摘要：基本工资、加班、扣款、实发",
        "inputSchema": {"type": "object", "properties": {"employeeData": {"type": "array"}, "period": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "competitor-brief",
        "name": "competitor-brief",
        "displayName": "竞品简报生成",
        "type": SkillType.PROMPT,
        "definition": "根据市场数据生成竞品简报：主要竞品动态、定价变化、市场份额趋势",
        "inputSchema": {"type": "object", "properties": {"marketData": {"type": "object"}, "competitors": {"type": "array"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "slack-digest",
        "name": "slack-digest",
        "displayName": "Slack消息摘要",
        "type": SkillType.PROMPT,
        "definition": "将Slack频道消息汇总为结构化摘要：关键讨论、决策、待办事项",
        "inputSchema": {"type": "object", "properties": {"messages": {"type": "array"}, "channelName": {"type": "string"}, "timeRange": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "invoice-validate",
        "name": "invoice-validate",
        "displayName": "发票合规校验",
        "type": SkillType.PROMPT,
        "definition": "校验发票合规性：金额匹配、税号有效、日期合理、重复检测",
        "inputSchema": {"type": "object", "properties": {"invoiceData": {"type": "object"}, "rules": {"type": "object"}}},
        "outputFormat": "json",
        "enabled": True,
    },
    {
        "skillId": "kpi-dashboard-data",
        "name": "kpi-dashboard-data",
        "displayName": "KPI仪表盘数据",
        "type": SkillType.PROMPT,
        "definition": "汇总业务KPI数据：营收、利润率、客户增长、 churn rate、ARPU",
        "inputSchema": {"type": "object", "properties": {"financialData": {"type": "object"}, "customerData": {"type": "object"}, "period": {"type": "string"}}},
        "outputFormat": "json",
        "enabled": True,
    },
]


def get_builtin_skills() -> list[Skill]:
    return [Skill(**s) for s in BUILTIN_SKILLS]
